part of 'preview_data.dart';

// Prices from the supplied shop photos. Existing prices absent from the photos
// are retained explicitly; see docs/SERVICE_CATALOG.md for pending confirmation.
final _defaultServiceCatalog = <PreviewService>[
  // existing
  _catalogService(
    'service-cs-reguler',
    'Cuci Setrika',
    'Cuci Setrika',
    'Reguler',
    'KG',
    7000,
    10,
    hours: 72,
    express: false,
  ),
  // existing
  _catalogService(
    'service-cs-express',
    'Cuci Setrika',
    'Cuci Setrika',
    'Express',
    'KG',
    9000,
    11,
    hours: 24,
    express: true,
  ),
  // existing
  _catalogService(
    'service-cs-kilat',
    'Cuci Setrika',
    'Cuci Setrika',
    'Kilat',
    'KG',
    12000,
    12,
    hours: 8,
    express: true,
  ),
  // existing
  _catalogService(
    'service-ckl-reguler',
    'Cuci Kering Lipat',
    'Cuci Kering Lipat',
    'Reguler',
    'KG',
    4000,
    20,
    hours: 72,
    express: false,
  ),
  // existing
  _catalogService(
    'service-ckl-express',
    'Cuci Kering Lipat',
    'Cuci Kering Lipat',
    'Express',
    'KG',
    6000,
    21,
    hours: 24,
    express: true,
  ),
  // existing
  _catalogService(
    'service-ckl-kilat',
    'Cuci Kering Lipat',
    'Cuci Kering Lipat',
    'Kilat',
    'KG',
    9000,
    22,
    hours: 8,
    express: true,
  ),
  // existing
  _catalogService(
    'service-sl-reguler',
    'Setrika Lipat',
    'Setrika Lipat',
    'Reguler',
    'KG',
    5000,
    30,
    hours: 72,
    express: false,
  ),
  // existing
  _catalogService(
    'service-sl-express',
    'Setrika Lipat',
    'Setrika Lipat',
    'Express',
    'KG',
    7000,
    31,
    hours: 24,
    express: true,
  ),
  // existing
  _catalogService(
    'service-sl-kilat',
    'Setrika Lipat',
    'Setrika Lipat',
    'Kilat',
    'KG',
    10000,
    32,
    hours: 8,
    express: true,
  ),
  // photo
  _catalogService(
    'service-pakaian-rok-cuci-setrika',
    'Pakaian',
    'Rok',
    'Cuci Setrika',
    'PIECE',
    15000,
    109,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-pakaian-rok-setrika-saja',
    'Pakaian',
    'Rok',
    'Setrika Saja',
    'PIECE',
    10000,
    110,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-pakaian-kemeja-cuci-setrika',
    'Pakaian',
    'Kemeja',
    'Cuci Setrika',
    'PIECE',
    15000,
    111,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-pakaian-kemeja-setrika-saja',
    'Pakaian',
    'Kemeja',
    'Setrika Saja',
    'PIECE',
    10000,
    112,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-pakaian-kerudung-kecil-s-m-l-cuci-setrika',
    'Pakaian',
    'Kerudung Kecil (S, M, L)',
    'Cuci Setrika',
    'PIECE',
    15000,
    113,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-pakaian-kerudung-kecil-s-m-l-setrika-saja',
    'Pakaian',
    'Kerudung Kecil (S, M, L)',
    'Setrika Saja',
    'PIECE',
    10000,
    114,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-pakaian-kerudung-besar-xl-xxl-cuci-setrika',
    'Pakaian',
    'Kerudung Besar (XL, XXL)',
    'Cuci Setrika',
    'PIECE',
    20000,
    115,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-pakaian-kerudung-besar-xl-xxl-setrika-saja',
    'Pakaian',
    'Kerudung Besar (XL, XXL)',
    'Setrika Saja',
    'PIECE',
    15000,
    116,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-pakaian-bandana',
    'Pakaian',
    'Bandana',
    '',
    'PIECE',
    5000,
    117,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-pakaian-daleman-baju-pengantin',
    'Pakaian',
    'Daleman Baju Pengantin',
    '',
    'PIECE',
    15000,
    118,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-pakaian-gaun-pengantin',
    'Pakaian',
    'Gaun Pengantin',
    '',
    'PIECE',
    50000,
    119,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-pakaian-kamisol',
    'Pakaian',
    'Kamisol',
    '',
    'PIECE',
    10000,
    120,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-pakaian-kamisol-anak',
    'Pakaian',
    'Kamisol Anak',
    '',
    'PIECE',
    5000,
    121,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-pakaian-pashmina',
    'Pakaian',
    'Pashmina',
    '',
    'PIECE',
    15000,
    122,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-pakaian-rompi',
    'Pakaian',
    'Rompi',
    '',
    'PIECE',
    15000,
    123,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-pakaian-rompi-anak',
    'Pakaian',
    'Rompi Anak',
    '',
    'PIECE',
    10000,
    124,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-pakaian-wearpack',
    'Pakaian',
    'Wearpack',
    '',
    'PIECE',
    20000,
    125,
    hours: 72,
    express: false,
  ),
  // existing
  _catalogService(
    'service-pakaian-kaos-sedang-normal',
    'Pakaian',
    'Kaos',
    'Sedang Normal',
    'PIECE',
    5000,
    126,
    hours: 72,
    express: false,
  ),
  // existing
  _catalogService(
    'service-pakaian-kaos-sedang-bagus',
    'Pakaian',
    'Kaos',
    'Sedang Bagus',
    'PIECE',
    7000,
    127,
    hours: 72,
    express: false,
  ),
  // existing
  _catalogService(
    'service-pakaian-kaos-besar-normal',
    'Pakaian',
    'Kaos',
    'Besar Normal',
    'PIECE',
    6000,
    128,
    hours: 72,
    express: false,
  ),
  // existing
  _catalogService(
    'service-pakaian-celana-panjang-normal',
    'Pakaian',
    'Celana Panjang',
    'Normal',
    'PIECE',
    20000,
    129,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-setelan-atasan-bawahan-kaos-celana-cuci-setrika',
    'Setelan (Atasan + Bawahan)',
    'Kaos + Celana',
    'Cuci Setrika',
    'SET',
    25000,
    130,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-setelan-atasan-bawahan-kaos-celana-setrika-saja',
    'Setelan (Atasan + Bawahan)',
    'Kaos + Celana',
    'Setrika Saja',
    'SET',
    15000,
    131,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-setelan-atasan-bawahan-kemeja-celana-panjang-cuci-setrika',
    'Setelan (Atasan + Bawahan)',
    'Kemeja + Celana Panjang',
    'Cuci Setrika',
    'SET',
    25000,
    132,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-setelan-atasan-bawahan-kemeja-celana-panjang-setrika-saja',
    'Setelan (Atasan + Bawahan)',
    'Kemeja + Celana Panjang',
    'Setrika Saja',
    'SET',
    15000,
    133,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-setelan-atasan-bawahan-jas-celana-panjang-cuci-setrika',
    'Setelan (Atasan + Bawahan)',
    'Jas + Celana Panjang',
    'Cuci Setrika',
    'SET',
    40000,
    134,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-setelan-atasan-bawahan-jas-celana-panjang-setrika-saja',
    'Setelan (Atasan + Bawahan)',
    'Jas + Celana Panjang',
    'Setrika Saja',
    'SET',
    25000,
    135,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-setelan-atasan-bawahan-kebaya-panjang-sarung-cuci-setrika',
    'Setelan (Atasan + Bawahan)',
    'Kebaya Panjang + Sarung',
    'Cuci Setrika',
    'SET',
    35000,
    136,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-setelan-atasan-bawahan-kebaya-panjang-sarung-setrika-saja',
    'Setelan (Atasan + Bawahan)',
    'Kebaya Panjang + Sarung',
    'Setrika Saja',
    'SET',
    25000,
    137,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-setelan-atasan-bawahan-kebaya-pendek-sarung-cuci-setrika',
    'Setelan (Atasan + Bawahan)',
    'Kebaya Pendek + Sarung',
    'Cuci Setrika',
    'SET',
    25000,
    138,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-setelan-atasan-bawahan-kebaya-pendek-sarung-setrika-saja',
    'Setelan (Atasan + Bawahan)',
    'Kebaya Pendek + Sarung',
    'Setrika Saja',
    'SET',
    15000,
    139,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-setelan-atasan-bawahan-baju-koko-sarung-cuci-setrika',
    'Setelan (Atasan + Bawahan)',
    'Baju Koko + Sarung',
    'Cuci Setrika',
    'SET',
    30000,
    140,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-setelan-atasan-bawahan-baju-koko-sarung-setrika-saja',
    'Setelan (Atasan + Bawahan)',
    'Baju Koko + Sarung',
    'Setrika Saja',
    'SET',
    20000,
    141,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-setelan-atasan-bawahan-baju-damkar-cuci-setrika',
    'Setelan (Atasan + Bawahan)',
    'Baju Damkar',
    'Cuci Setrika',
    'SET',
    25000,
    142,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-jas-dan-jaket-jas-cuci-setrika',
    'Jas dan Jaket',
    'Jas',
    'Cuci Setrika',
    'PIECE',
    25000,
    143,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-jas-dan-jaket-jas-setrika-saja',
    'Jas dan Jaket',
    'Jas',
    'Setrika Saja',
    'PIECE',
    15000,
    144,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-jas-dan-jaket-blazer-cuci-setrika',
    'Jas dan Jaket',
    'Blazer',
    'Cuci Setrika',
    'PIECE',
    25000,
    145,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-jas-dan-jaket-jaket-cuci-setrika',
    'Jas dan Jaket',
    'Jaket',
    'Cuci Setrika',
    'PIECE',
    20000,
    146,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-jas-dan-jaket-jaket-setrika-saja',
    'Jas dan Jaket',
    'Jaket',
    'Setrika Saja',
    'PIECE',
    15000,
    147,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-jas-dan-jaket-hoodie-cuci-setrika',
    'Jas dan Jaket',
    'Hoodie',
    'Cuci Setrika',
    'PIECE',
    20000,
    148,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-jas-dan-jaket-hoodie-setrika-saja',
    'Jas dan Jaket',
    'Hoodie',
    'Setrika Saja',
    'PIECE',
    15000,
    149,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-jas-dan-jaket-sweater-cuci-setrika',
    'Jas dan Jaket',
    'Sweater',
    'Cuci Setrika',
    'PIECE',
    20000,
    150,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-jas-dan-jaket-sweater-setrika-saja',
    'Jas dan Jaket',
    'Sweater',
    'Setrika Saja',
    'PIECE',
    15000,
    151,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-jas-dan-jaket-jaket-kulit',
    'Jas dan Jaket',
    'Jaket Kulit',
    '',
    'PIECE',
    50000,
    152,
    hours: 72,
    express: false,
  ),
  // existing
  _catalogService(
    'service-jas-dan-jaket-jaket-tebal-bulu',
    'Jas dan Jaket',
    'Jaket',
    'Tebal/Bulu',
    'PIECE',
    35000,
    153,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-perlengkapan-tidur-sprei-besar-160-180-200-cuci-setrika',
    'Perlengkapan Tidur',
    'Sprei Besar (160, 180, 200)',
    'Cuci Setrika',
    'PIECE',
    15000,
    154,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-perlengkapan-tidur-sprei-besar-160-180-200-setrika-saja',
    'Perlengkapan Tidur',
    'Sprei Besar (160, 180, 200)',
    'Setrika Saja',
    'PIECE',
    9000,
    155,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-perlengkapan-tidur-sprei-balon-cuci-setrika',
    'Perlengkapan Tidur',
    'Sprei Balon',
    'Cuci Setrika',
    'PIECE',
    20000,
    156,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-perlengkapan-tidur-sprei-balon-setrika-saja',
    'Perlengkapan Tidur',
    'Sprei Balon',
    'Setrika Saja',
    'PIECE',
    12000,
    157,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-perlengkapan-tidur-selimut-kecil-90-100-120-cuci-setrika',
    'Perlengkapan Tidur',
    'Selimut Kecil (90, 100, 120)',
    'Cuci Setrika',
    'PIECE',
    10000,
    158,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-perlengkapan-tidur-selimut-kecil-90-100-120-setrika-saja',
    'Perlengkapan Tidur',
    'Selimut Kecil (90, 100, 120)',
    'Setrika Saja',
    'PIECE',
    6000,
    159,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-perlengkapan-tidur-selimut-besar-160-180-200-cuci-setrika',
    'Perlengkapan Tidur',
    'Selimut Besar (160, 180, 200)',
    'Cuci Setrika',
    'PIECE',
    15000,
    160,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-perlengkapan-tidur-selimut-besar-160-180-200-setrika-saja',
    'Perlengkapan Tidur',
    'Selimut Besar (160, 180, 200)',
    'Setrika Saja',
    'PIECE',
    9000,
    161,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-perlengkapan-tidur-alas-kasur-springbed',
    'Perlengkapan Tidur',
    'Alas Kasur Springbed',
    '',
    'PIECE',
    15000,
    162,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-perlengkapan-tidur-kelambu-tempat-tidur-besar',
    'Perlengkapan Tidur',
    'Kelambu Tempat Tidur Besar',
    '',
    'PIECE',
    25000,
    163,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-perlengkapan-tidur-kelambu-tempat-tidur-sedang',
    'Perlengkapan Tidur',
    'Kelambu Tempat Tidur Sedang',
    '',
    'PIECE',
    20000,
    164,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-perlengkapan-tidur-kelambu-tempat-tidur-kecil',
    'Perlengkapan Tidur',
    'Kelambu Tempat Tidur Kecil',
    '',
    'PIECE',
    15000,
    165,
    hours: 72,
    express: false,
  ),
  // existing
  _catalogService(
    'service-perlengkapan-tidur-sprei-small',
    'Perlengkapan Tidur',
    'Sprei',
    'Small',
    'PIECE',
    10000,
    166,
    hours: 72,
    express: false,
  ),
  // existing
  _catalogService(
    'service-perlengkapan-tidur-sprei-medium',
    'Perlengkapan Tidur',
    'Sprei',
    'Medium',
    'PIECE',
    13000,
    167,
    hours: 72,
    express: false,
  ),
  // existing
  _catalogService(
    'service-perlengkapan-tidur-bed-cover-sedang-katun',
    'Perlengkapan Tidur',
    'Bed Cover',
    'Sedang Katun',
    'PIECE',
    35000,
    168,
    hours: 72,
    express: false,
  ),
  // existing
  _catalogService(
    'service-perlengkapan-tidur-bed-cover-besar-katun',
    'Perlengkapan Tidur',
    'Bed Cover',
    'Besar Katun',
    'PIECE',
    50000,
    169,
    hours: 72,
    express: false,
  ),
  // existing
  _catalogService(
    'service-perlengkapan-tidur-bed-cover-besar-bulu-angsa',
    'Perlengkapan Tidur',
    'Bed Cover',
    'Besar Bulu Angsa',
    'PIECE',
    130000,
    170,
    hours: 72,
    express: false,
  ),
  // existing
  _catalogService(
    'service-perlengkapan-tidur-selimut-tebal',
    'Perlengkapan Tidur',
    'Selimut',
    'Tebal',
    'PIECE',
    15000,
    171,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-handuk-handuk-kecil',
    'Handuk',
    'Handuk',
    'Kecil',
    'PIECE',
    10000,
    172,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-handuk-handuk-sedang',
    'Handuk',
    'Handuk',
    'Sedang',
    'PIECE',
    15000,
    173,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-handuk-handuk-besar',
    'Handuk',
    'Handuk',
    'Besar',
    'PIECE',
    20000,
    174,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-perlengkapan-ibadah-mukena-cuci-setrika',
    'Perlengkapan Ibadah',
    'Mukena',
    'Cuci Setrika',
    'SET',
    20000,
    175,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-perlengkapan-ibadah-mukena-setrika-saja',
    'Perlengkapan Ibadah',
    'Mukena',
    'Setrika Saja',
    'SET',
    15000,
    176,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-perlengkapan-ibadah-sajadah-tipis-cuci-setrika',
    'Perlengkapan Ibadah',
    'Sajadah Tipis',
    'Cuci Setrika',
    'PIECE',
    10000,
    177,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-perlengkapan-ibadah-sajadah-tipis-setrika-saja',
    'Perlengkapan Ibadah',
    'Sajadah Tipis',
    'Setrika Saja',
    'PIECE',
    6000,
    178,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-perlengkapan-ibadah-sajadah-tebal-cuci-setrika',
    'Perlengkapan Ibadah',
    'Sajadah Tebal',
    'Cuci Setrika',
    'PIECE',
    15000,
    179,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-perlengkapan-ibadah-sajadah-tebal-setrika-saja',
    'Perlengkapan Ibadah',
    'Sajadah Tebal',
    'Setrika Saja',
    'PIECE',
    9000,
    180,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-perlengkapan-bayi-alas-box-bayi',
    'Perlengkapan Bayi',
    'Alas Box Bayi',
    '',
    'PIECE',
    20000,
    181,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-perlengkapan-bayi-alas-keranjang-bayi',
    'Perlengkapan Bayi',
    'Alas Keranjang Bayi',
    '',
    'PIECE',
    10000,
    182,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-perlengkapan-bayi-baby-walker',
    'Perlengkapan Bayi',
    'Baby Walker',
    '',
    'PIECE',
    30000,
    183,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-perlengkapan-bayi-bemper-bayi-kecil',
    'Perlengkapan Bayi',
    'Bemper Bayi Kecil',
    '',
    'PIECE',
    15000,
    184,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-perlengkapan-bayi-bemper-bayi-sedang',
    'Perlengkapan Bayi',
    'Bemper Bayi Sedang',
    '',
    'PIECE',
    20000,
    185,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-perlengkapan-bayi-boks-bayi',
    'Perlengkapan Bayi',
    'Boks Bayi',
    '',
    'PIECE',
    50000,
    186,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-perlengkapan-bayi-busa-alas-keranjang-bayi',
    'Perlengkapan Bayi',
    'Busa Alas Keranjang Bayi',
    '',
    'PIECE',
    15000,
    187,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-perlengkapan-bayi-perlak',
    'Perlengkapan Bayi',
    'Perlak',
    '',
    'PIECE',
    15000,
    188,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-perlengkapan-rumah-alas-piring-meja-makan',
    'Perlengkapan Rumah',
    'Alas Piring Meja Makan',
    '',
    'PIECE',
    5000,
    189,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-perlengkapan-rumah-alas-sofa',
    'Perlengkapan Rumah',
    'Alas Sofa',
    '',
    'PIECE',
    10000,
    190,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-perlengkapan-rumah-bantal-kursi',
    'Perlengkapan Rumah',
    'Bantal Kursi',
    '',
    'PIECE',
    15000,
    191,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-perlengkapan-rumah-bantal-lantai',
    'Perlengkapan Rumah',
    'Bantal Lantai',
    '',
    'PIECE',
    20000,
    192,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-perlengkapan-rumah-bantalan-tempat-duduk',
    'Perlengkapan Rumah',
    'Bantalan Tempat Duduk',
    '',
    'PIECE',
    30000,
    193,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-perlengkapan-rumah-kap-lampu-besar',
    'Perlengkapan Rumah',
    'Kap Lampu Besar',
    '',
    'PIECE',
    20000,
    194,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-perlengkapan-rumah-kap-lampu-sedang',
    'Perlengkapan Rumah',
    'Kap Lampu Sedang',
    '',
    'PIECE',
    15000,
    195,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-perlengkapan-rumah-keset-tebal',
    'Perlengkapan Rumah',
    'Keset Tebal',
    '',
    'PIECE',
    10000,
    196,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-perlengkapan-rumah-keset-tipis',
    'Perlengkapan Rumah',
    'Keset Tipis',
    '',
    'PIECE',
    5000,
    197,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-perlengkapan-rumah-tikar',
    'Perlengkapan Rumah',
    'Tikar',
    '',
    'PIECE',
    25000,
    198,
    hours: 72,
    express: false,
  ),
  // existing
  _catalogService(
    'service-perlengkapan-rumah-karpet-per-m2',
    'Perlengkapan Rumah',
    'Karpet',
    'per m2',
    'M2',
    47000,
    199,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-kain-dan-gorden-kain-3-m',
    'Kain dan Gorden',
    'Kain (<3 m)',
    '',
    'PIECE',
    15000,
    200,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-kain-dan-gorden-kain-pantai',
    'Kain dan Gorden',
    'Kain Pantai',
    '',
    'PIECE',
    15000,
    201,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-kain-dan-gorden-kain-payung',
    'Kain dan Gorden',
    'Kain Payung',
    '',
    'PIECE',
    15000,
    202,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-kain-dan-gorden-kain-songket',
    'Kain dan Gorden',
    'Kain Songket',
    '',
    'PIECE',
    15000,
    203,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-kain-dan-gorden-kain-ulos',
    'Kain dan Gorden',
    'Kain Ulos',
    '',
    'PIECE',
    15000,
    204,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-kain-dan-gorden-gorden',
    'Kain dan Gorden',
    'Gorden',
    '',
    'M2',
    15000,
    205,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-kain-dan-gorden-gorden-setrika-saja',
    'Kain dan Gorden',
    'Gorden',
    'Setrika Saja',
    'M2',
    9000,
    206,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-tas-tas-ransel-kecil',
    'Tas',
    'Tas Ransel',
    'Kecil',
    'PIECE',
    10000,
    207,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-tas-tas-ransel-sedang',
    'Tas',
    'Tas Ransel',
    'Sedang',
    'PIECE',
    15000,
    208,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-tas-tas-ransel-besar',
    'Tas',
    'Tas Ransel',
    'Besar',
    'PIECE',
    20000,
    209,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-perlengkapan-kendaraan-bantalan-sandaran-mobil',
    'Perlengkapan Kendaraan',
    'Bantalan Sandaran Mobil',
    '',
    'PIECE',
    10000,
    210,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-perlengkapan-kendaraan-cover-tutup-mobil',
    'Perlengkapan Kendaraan',
    'Cover (Tutup) Mobil',
    '',
    'PIECE',
    25000,
    211,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-perlengkapan-kendaraan-cover-tutup-motor',
    'Perlengkapan Kendaraan',
    'Cover (Tutup) Motor',
    '',
    'PIECE',
    20000,
    212,
    hours: 72,
    express: false,
  ),
  // existing
  _catalogService(
    'service-boneka-boneka-xs',
    'Boneka',
    'Boneka',
    'XS',
    'PIECE',
    38000,
    213,
    hours: 72,
    express: false,
  ),
  // existing
  _catalogService(
    'service-boneka-boneka-s',
    'Boneka',
    'Boneka',
    'S',
    'PIECE',
    45000,
    214,
    hours: 72,
    express: false,
  ),
  // existing
  _catalogService(
    'service-boneka-boneka-m',
    'Boneka',
    'Boneka',
    'M',
    'PIECE',
    53000,
    215,
    hours: 72,
    express: false,
  ),
  // existing
  _catalogService(
    'service-boneka-boneka-l',
    'Boneka',
    'Boneka',
    'L',
    'PIECE',
    67000,
    216,
    hours: 72,
    express: false,
  ),
  // existing
  _catalogService(
    'service-boneka-boneka-xl',
    'Boneka',
    'Boneka',
    'XL',
    'PIECE',
    158000,
    217,
    hours: 72,
    express: false,
  ),
  // existing-app
  _catalogService(
    'service-sepatu-reguler',
    'Sepatu',
    'Cuci Sepatu',
    'Reguler',
    'PAIR',
    25000,
    218,
    hours: 72,
    express: false,
  ),
  // existing-app
  _catalogService(
    'service-helm-reguler',
    'Helm',
    'Cuci Helm',
    'Reguler',
    'ITEM',
    20000,
    219,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-lainnya-bendera-besar',
    'Lainnya',
    'Bendera Besar',
    '',
    'PIECE',
    20000,
    220,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-lainnya-bendera-kecil',
    'Lainnya',
    'Bendera Kecil',
    '',
    'PIECE',
    15000,
    221,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-lainnya-body-protector',
    'Lainnya',
    'Body Protector',
    '',
    'PIECE',
    50000,
    222,
    hours: 72,
    express: false,
  ),
  // photo
  _catalogService(
    'service-lainnya-bendera-meteran',
    'Lainnya',
    'Bendera',
    'Meteran',
    'M2',
    5000,
    223,
    hours: 72,
    express: false,
  ),
  // existing-app
  _catalogService(
    'service-extra-express',
    'Layanan Tambahan',
    'Express',
    'Tambahan',
    'ITEM',
    5000,
    224,
    hours: 24,
    express: true,
  ),
  // existing-app
  _catalogService(
    'service-extra-noda-berat',
    'Layanan Tambahan',
    'Noda Berat',
    'Tambahan',
    'ITEM',
    5000,
    225,
    hours: 72,
    express: false,
  ),
];

PreviewService _catalogService(
  String id,
  String category,
  String item,
  String variant,
  String unit,
  int price,
  int sortOrder, {
  int hours = 72,
  bool express = false,
}) => PreviewService(
  id: id,
  name: variant.isEmpty ? item : '$item $variant',
  category: category,
  unit: unit,
  price: price,
  estimatedHours: hours,
  isExpress: express,
  isActive: true,
  categoryName: category,
  itemName: item,
  variantName: variant,
  sortOrder: sortOrder,
);
